logging:
  log_file: "pipeline_execution.log"
  level: "INFO"

dataset:
  raw_path: "data/raw/combined_reviews.csv"
  processed_path: "data/processed/reviews_processed.parquet"
  social_data_path: "data/processed/social_media_data.parquet"

social_media:
  tiktok_hashtags: ["skincare", "makeup", "beauty", "sephora", "fragrance", "haircare", "beautytips", "cosmetics"]
  instagram_hashtags: ["skincare", "makeup", "beautyblogger", "sephora", "perfume", "haircare", "beautyproducts"]